ECOM.PortalWWW/Controllers/AktualnoscController.cs
using Firma.Data.Data;
using Firma.Data.Data.CMS;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Firma.Intranet.Controllers
{
    public class AktualnoscController : Controller
    {
        private readonly FirmaContext _context;

        public AktualnoscController(FirmaContext context)
        {
            _context = context;
        }

        // GET: Aktualnosc
        public async Task<IActionResult> Index()
        {
              return View(await _context.Aktualnosc.ToListAsync());
        }

        // GET: Aktualnosc/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Aktualnosc == null)
            {
                return NotFound();
            }

            var aktualnosc = await _context.Aktualnosc
                .FirstOrDefaultAsync(m => m.IdAktualnosci == id);
            if (aktualnosc == null)
            {
                return NotFound();
            }

            return View(aktualnosc);
        }

        // GET: Aktualnosc/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Aktualnosc/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAktualnosci,LinkTytul,Tytul,Tresc,Pozycja")] Aktualnosc aktualnosc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aktualnosc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aktualnosc);
        }

        // GET: Aktualnosc/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Aktualnosc == null)
            {
                return NotFound();
            }

            var aktualnosc = await _context.Aktualnosc.FindAsync(id);
            if (aktualnosc == null)
            {
                return NotFound();
            }
            return View(aktualnosc);
        }

        // POST: Aktualnosc/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAktualnosci,LinkTytul,Tytul,Tresc,Pozycja")] Aktualnosc aktualnosc)
        {
            if (id != aktualnosc.IdAktualnosci)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aktualnosc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AktualnoscExists(aktualnosc.IdAktualnosci))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aktualnosc);
        }

        // GET: Aktualnosc/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Aktualnosc == null)
            {
                return NotFound();
            }

            var aktualnosc = await _context.Aktualnosc
                .FirstOrDefaultAsync(m => m.IdAktualnosci == id);
            if (aktualnosc == null)
            {
                return NotFound();
            }

            return View(aktualnosc);
        }

        // POST: Aktualnosc/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Aktualnosc == null)
            {
                return Problem("Entity set 'FirmaContext.Aktualnosc'  is null.");
            }
            var aktualnosc = await _context.Aktualnosc.FindAsync(id);
            if (aktualnosc != null)
            {
                _context.Aktualnosc.Remove(aktualnosc);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AktualnoscExists(int id)
        {
          return _context.Aktualnosc.Any(e => e.IdAktualnosci == id);
        }
    }
}

ECOM.PortalWWW/Controllers/SklepController.cs
using Firma.Data.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ECOM.PortalWWW.Controllers
{
    public class SklepController : Controller
    {
        private readonly FirmaContext _context;

        public SklepController(FirmaContext context)
        {
            _context = context;
        }
        
        /// w zmiennej id bedzie przekazywane id categorii kliknietego rodzaju towaru.
        public async Task<IActionResult> Index(int? id)
        {
            // Za pomoca view baga przekazujemy do widoku wszystkie rodzaje towarow.
            //ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();
            // Przy pierwszym wejsciu do sklepu id rodzaju towaru bedzie puste, zatem domyslnie podstawimy tam pierwszy rodzaj.
            if(id == null)
            {
                var pierwszy = await _context.Rodzaj.FirstAsync();
                id = pierwszy.IdRodzaju;
            }
            // do widoku przekazujemy wszystkie to wary danego kliknietego rodzaju.
            return View(await _context.Towar.Where(item =>item.RodzajId == id).ToListAsync());
        }

        //to jest funkcja ktora wystawia dane do widoku wyswietlajacego szczegoly towaru.
        public async Task<IActionResult> Details(int id) // w parametrze id jest okreslone id towaru ktorego szczegoly mamy wyswietlic.
        {
            //ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();
            //do widoku przekazujemy towar o danym kliknietym id.
            return View(await _context.Towar.FirstOrDefaultAsync(item => item.IdTowaru == id));
        }
    }
}

ECOM.PortalWWW/Views/Shared/RodzajeMenu.cshtml
@model IEnumerable<Firma.Data.Data.Sklep.Rodzaj>

ECOM.PortalWWW/Views/Shared/_KoszykLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <title>Starter Template - Materialize</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/lib/materialize/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/lib/materialize/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    @RenderSection("head", required: false)
</head>
<body>
    <nav class="light-blue lighten-1" role="navigation">
        <ul class="right hide-on-med-and-down">
            <li>
                <a asp-action="Index" asp-controller="Sklep">Sklep</a>
            </li>
        </ul>
    </nav>
    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            @RenderBody()
        </div>
    </div>

    <footer class="page-footer orange">

        <div class="footer-copyright">
            <div class="container">
                Made by KJS<a class="orange-text text-lighten-3" href="http://materializecss.com"></a>
            </div>
        </div>
    </footer>


    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="../../bin/materialize.js"></script>
    <script src="js/init.js"></script>

</body>
</html>

ECOM.PortalWWW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <title>Starter Template - Materialize</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/lib/materialize/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/lib/materialize/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    @RenderSection("head", required: false)
</head>
<style>
    .class1 {
  width: 100%;
  height: 70px;
  background-color: #F8B195; /* default background color */
  animation: colorChange 5s infinite alternate; /* CSS animation */
}

@@keyframes colorChange {
  0% {
    background-color: #F8B195;
  }
  50% {
    background-color: #7ED6DF;
  }
  100% {
    background-color: #9B4DCA;
  }
}
</style>
<body>
    <nav class="class1" role="navigation">
        @await Component.InvokeAsync("OdnosnikiComponent")
       @* <div class="nav-wrapper container">
            <a id="logo-container" href="#" class="brand-logo">Logo</a>
            <ul class="right hide-on-med-and-down">
                <li>@Html.ActionLink("Main Page", "Index", "Home")</li>
                <li>@Html.ActionLink("Sklep internetowy", "Index", "Sklep")</li>
                <li>@Html.ActionLink("About", "Aktualnosc", "Aktualnosc")</li>
                <li></li>
            </ul>

            <ul id="nav-mobile" class="sidenav">
                <li><a href="#">Navbar Link</a></li>
            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>*@
    </nav>
    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            @await Component.InvokeAsync("AktualnoscComponent")
           @RenderBody()
        </div>
    </div>


    <div class="container">
        <div class="section">

            <!--   Icon Section   -->
            <div class="row">
                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
                        <h5 class="center">Ecom is a company</h5>

                        <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
                    </div>
                </div>

                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
                        <h5 class="center">About Products</h5>

                        <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
                    </div>
                </div>

                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
                        <h5 class="center">About the shop</h5>

                        <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
                    </div>
                </div>
            </div>

        </div>
        <br><br>
    </div>

    <footer class="page-footer orange">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">ECOM</h5>
                    <p class="grey-text text-lighten-4">WSB-NLU Course</p>
                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Information</h5>
                    <ul>
                        <li>@Html.ActionLink("Privacy", "Privacy", "Home")</li>
                        <li>@Html.ActionLink("Koszyk", "Index", "Koszyk")</li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                    </ul>
                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Connect</h5>
                    <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                        <li><a class="white-text" href="#!">Link 2</a></li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Made by KJS<a class="orange-text text-lighten-3" href="http://materializecss.com"></a>
            </div>
        </div>
    </footer>


    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="../../bin/materialize.js"></script>
    <script src="js/init.js"></script>

</body>
</html>

ECOM.PortalWWW/Views/Shared/_sklepLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <title>Starter Template - Materialize</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/lib/materialize/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/lib/materialize/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    @RenderSection("head", required: false)
</head>
<body>
    <nav class="light-blue lighten-1" role="navigation">
        @await Component.InvokeAsync("RodzajeMenuComponent")
       @* <div class="nav-wrapper container">
            <a id="logo-container" href="#" class="brand-logo">Logo</a>
            <ul class="right hide-on-med-and-down">
                <li>@Html.ActionLink("Main Page", "Index", "Home")</li>
                <li>@Html.ActionLink("Sklep internetowy", "Index", "Sklep")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li></li>
            </ul>

            <ul id="nav-mobile" class="sidenav">
                <li><a href="#">Navbar Link</a></li>
            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>*@
    </nav>
    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            @RenderBody()
        </div>
    </div>

    <footer class="page-footer orange">
       
        <div class="footer-copyright">
            <div class="container">
                Made by KJS<a class="orange-text text-lighten-3" href="http://materializecss.com"></a>
            </div>
        </div>
    </footer>


    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="../../bin/materialize.js"></script>
    <script src="js/init.js"></script>

</body>
</html>