ECOM.PortalWWW/Models/Sklep/DaneDoKoszyka.cs
using Firma.Data.Data.Sklep;

namespace ECOM.PortalWWW.Models.Sklep
{
	// to jest klasa pomocnicza ktora bedzie sluzyla do tego zeby poprawnie
	// wyswietlac koszyk.
	public class DaneDoKoszyka
	{
        // w celu wyswietlenia koszyka mam liste elementow koszyka oraz jego sumaryczna wartosc.
        public List<ElementKoszyka> ElementyKoszyka { get; set; }
        public decimal Razem { get; set; }

    }
}

ECOM.PortalWWW/Controllers/KoszykController.cs
using ECOM.PortalWWW.Models.BusinessLogic;
using ECOM.PortalWWW.Models.Sklep;
using Firma.Data.Data;
using Microsoft.AspNetCore.Mvc;

namespace ECOM.PortalWWW.Controllers
{
	public class KoszykController : Controller
	{
		private readonly FirmaContext _context;

        public KoszykController(FirmaContext context)
        {
            _context = context;
        }

		//Ta funkcja wystawia dane do wyswietlania koszyka
        public async Task<IActionResult> Index()
		{
			KoszykB koszykB = new KoszykB(this._context, this.HttpContext);
			DaneDoKoszyka dane = new DaneDoKoszyka()
			{
				ElementyKoszyka = await koszykB.GetElementyKoszyka(),
				Razem = await koszykB.GetWartoscKoszyka()
			};
			return View(dane);
		}

		public async Task<IActionResult> DodajDoKoszyka(int id)
		{
			KoszykB koszykB = new KoszykB(this._context, this.HttpContext);
			koszykB.DodajDoKoszyka(await _context.Towar.FindAsync(id));
			return RedirectToAction("Index");
		}
	}
}

ECOM.PortalWWW/Controllers/SklepController.cs
using Firma.Data.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ECOM.PortalWWW.Controllers
{
    public class SklepController : Controller
    {
        private readonly FirmaContext _context;

        public SklepController(FirmaContext context)
        {
            _context = context;
        }
        
        /// w zmiennej id bedzie przekazywane id categorii kliknietego rodzaju towaru.
        public async Task<IActionResult> Index(int? id)
        {
            // Za pomoca view baga przekazujemy do widoku wszystkie rodzaje towarow.
            //ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();
            // Przy pierwszym wejsciu do sklepu id rodzaju towaru bedzie puste, zatem domyslnie podstawimy tam pierwszy rodzaj.
            if(id == null)
            {
                var pierwszy = await _context.Rodzaj.FirstAsync();
                id = pierwszy.IdRodzaju;
            }
            // do widoku przekazujemy wszystkie to wary danego kliknietego rodzaju.
            return View(await _context.Towar.Where(item =>item.RodzajId == id).ToListAsync());
        }

        //to jest funkcja ktora wystawia dane do widoku wyswietlajacego szczegoly towaru.
        public async Task<IActionResult> Details(int id) // w parametrze id jest okreslone id towaru ktorego szczegoly mamy wyswietlic.
        {
            //ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();
            //do widoku przekazujemy towar o danym kliknietym id.
            return View(await _context.Towar.FirstOrDefaultAsync(item => item.IdTowaru == id));
        }
    }
}

ECOM.PortalWWW/Views/Sklep/Details.cshtml
@model Firma.Data.Data.Sklep.Towar
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_sklepLayout.cshtml";
}
<style>
    .diver {
        display: flex;
        flex-direction: column;
        width: 100%;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
        width: 200px;
    }

        /* Ustawienie stylów dla pierwszego bloku div */
        .diver div:first-of-type {
            background-color: #45b6fe;
            color: #fff;
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            padding: 10px;
        }

        /* Ustawienie stylów dla pozostałych bloków div */
        .diver div:not(:first-of-type) {
            padding: 10px;
        }

        /* Ustawienie stylów dla drugiego bloku div */
        .diver div:nth-of-type(2) {
            font-size: 20px;
            font-weight: bold;
        }

        /* Ustawienie stylów dla czwartego bloku div */
        .diver div:nth-of-type(4) {
            font-size: 18px;
            color: #45b6fe;
            font-weight: bold;
        }

        /* Ustawienie stylów dla piątego bloku div */
        .diver div:last-of-type {
            font-size: 16px;
            line-height: 1.5;
        }
</style>
<center>
    <div class="diver">
        <div>
            <img src="https://www.corsair.com/corsairmedia/sys_master/productcontent/CH-9300011-NA-M65_PRO_RGB_BLK_04.png" alt="mouse corsair" class="mouse" style="width:70px; height:100px;">
        </div>
        <table>
            <tr>
                <td>
                    <div>
                        Nazwa
                    </div>
                </td>
                <td>
                    <div>
                        @Model.Nazwa
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        Kod
                    </div>
                </td>
                <td>
                    <div>
                        @Model.Kod
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        Cena
                    </div>
                </td>
                <td>
                    <div>
                        @Model.Cena.ToString("0.00") $
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        Opis
                    </div>
                </td>
                <td>
                    <div>
                        @Model.Opis
                    </div>
                </td>
            </tr>
        </table>
        <div style="color:white;">
            @Html.ActionLink("Cofnij", "Index", "Sklep", new { @class = "btn btn-info btn-icon", style = "color: white;" })
        </div>
        <div style="color:white;">
            <a asp-action="DodajDoKoszyka" asp-controller="Koszyk" asp-route-id="@Model.IdTowaru">Dodaj do koszyka</a>
        </div>
    </div>
    <br />
    
</center>
<br />

ECOM.PortalWWW/Views/Sklep/Index.cshtml
@model IEnumerable<Firma.Data.Data.Sklep.Towar>
@{
    ViewData["Title"] = "Sklep";
    Layout = "~/Views/Shared/_sklepLayout.cshtml";
}
@section head {
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/reset.css"> <!-- CSS reset -->
    <script src="js/modernizr.js"></script> <!-- Modernizr -->
    <link href="~/css/home.css" type="text/css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="~/css/index.css" type="text/css" rel="stylesheet" />
    <link href="~/css/layout.css" type="text/css" rel="stylesheet" />
}
<style>
    .card {
        border: 1px solid #ddd;
        border-radius: 4px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        padding: 20px;
        width: 400px;
    }

    .card-header h3 {
        margin-top: 0;
        margin-bottom: 20px;
    }
    .card btn{
        background-color: #007bff;;
    }
</style>
<script>
    function performAction() {
        var url = '@Url.Action("Details", "Sklep")';
        window.location.href = url;
    }
</script>
<div>
    <table>
        @*<thead>
            <tr>
                <th>Foto</th>
                <th>Nazwa</th>
                <th>Cena</th>
            </tr>
        </thead>*@
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        <div class="card" style="width:200px;">
                            <div class="card-header">
                                <div>
                                    @Html.ActionLink("Info", "Details", "Sklep", new{id = item.IdTowaru}, new { @class = "btn btn-info btn-icon" })
                                </div>
                            </div>
                            <div class="card-body" style="margin-left:70px;">
                                <img src="https://www.corsair.com/corsairmedia/sys_master/productcontent/CH-9300011-NA-M65_PRO_RGB_BLK_04.png" alt="mouse corsair" class="mouse" style="width:70px; height:100px;">
                                
                            </div>
                            <h5>@item.Nazwa</h5>
                            <h5 class="price">@item.Cena.ToString("0.00") £</h5>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>